#!/usr/bin/env bash

path=$(dirname $(readlink -n -f $0))

mkdir -p ~/.vim
ln -s $path/colors ~/.vim/
ln -s $path/syntax ~/.vim/
ln -s $path/ftdetect ~/.vim/
ln -s $path/autoload ~/.vim/
ln -s $path/autoload ~/.vim/plugin
ln -s $path/vimrc ~/.vimrc
